### ISSUE TITLE
Marginal plot scales.

### ISSUE THREAD

**Issue by jacekkotowski** [WinVector/WVPlots#2]
Grids... They do not correspond to main plot grid.  I wish you lots of success.

**Comment by JohnMount** [comment]
We know there are no shared data coordinates to line up with.  We try to over-control the format (setting bounds, adding leading underbars to text) to try and get things to line up by the formatting side-effects.   Some notes on the effort are here: http://www.win-vector.com/blog/2015/06/wanted-a-perfect-scatterplot-with-marginals/ .  I think we have now fixed the issue you likely saw as of https://github.com/WinVector/WVPlots/commit/315c1b8b39a8e55691b865541e2538b24c653e19 and it is related to coord_flip() clearing some commands (which surprised us https://github.com/tidyverse/ggplot2/issues/2013  , but evidently is as specified as as ggplot 2 2.2.0, but wasn't the case when we first QAed the plots).
