### ISSUE TITLE
annotation text size

### ISSUE THREAD

**Issue by quinzlib** [WinVector/WVPlots#3]
Hi, I am trying to create a ~large 6x11 plot using grid.arrange and have been able to edit most of the text elements in the ShadedDensityCenter figures using theme(). I have not been able to adjust the annotation text size and wonder if there is an easy solution that I am just not finding. The figure is **almost** perfect but the annotation text is so large that it does not fit. 

Thank you, 

Jenn

The code in case it is useful: 
```
test = lapply(names(ef_df), function(colname) {
 threshold <- c(quantile(ef_df[, colname], c(0))[[1]],0)
  WVPlots::ShadedDensityCenter(frame = ef_df, 
                               xvar = colname,
                               boundaries  = threshold,
                               title = colname, 
                               shading = "darkred") +
    theme(plot.title = element_text(hjust = 0.5,size = 10),
          axis.title.x = element_blank(),
          axis.title.y = element_blank()) 
  
})

gridExtra::grid.arrange(grobs = test,ncol=5, bottom = "Region Pair Group Differences", left= "Density") 

```

**Comment by JohnMount** [comment]
Sorry to not have a good answer. It is really punishing (and unstable) to try and work with ggplot2's stylers. Perhaps something that is close to what you want is in this package here: https://cran.r-project.org/package=ggstatsplot .
