### ISSUE TITLE
Dot-dot notation deprecated in ggplot2 3.4.0

### ISSUE THREAD

**Issue by NunonuN** [WinVector/WVPlots#5]
I'm getting the following warning message:

```
Warning message:
The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.
ℹ The deprecated feature was likely used in the WVPlots package.
```

Congrats for the great package. Keep up the good work.

**Comment by JohnMount** [comment]
Thank you for the (nice!) issue report, and sorry about any trouble. We will try and find where that is in the package.

**Comment by JohnMount** [comment]
ref: https://www.tidyverse.org/blog/2020/03/ggplot2-3-3-0/

**Comment by JohnMount** [comment]
fixed and pushing to CRAN
